backend:
  name: github
  branch: main
  repo: inclusive-design/acaw-cama
  base_url: https://sveltia-cms-auth.idrc-ops.workers.dev
media_folder: src/assets/uploads
public_folder: /assets/uploads

editor:
  preview: false
i18n:
  locales: [en, fr]
  default_locale: en
collections:
  - label: Pages
    label_singular: Page
    name: pages
    icon: article
    i18n:
      structure: multiple_folders
    folder: src/collections/pages/
    extension: md
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Excerpt, name: excerpt, widget: string, required: false, i18n: true}
      - {label: Body, name: body, widget: markdown, i18n: true}
  - label: Presentations
    label_singular: Presentation
    name: presentations
    icon: co_present
    i18n:
      structure: multiple_folders
    folder: src/collections/presentations/
    extension: md
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Tags, name: tags, widget: relation, multiple: true, collection: tags, search_fields: [title], value_field: uuid, display_fields: [title], i18n: duplicate}
      - {label: Body, name: body, widget: markdown, i18n: true}
  - label: Tags
    label_singular: Tag
    name: tags
    icon: sell
    i18n:
      structure: multiple_folders
    folder: src/collections/tags/
    extension: md
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: ID, name: uuid, widget: uuid, i18n: duplicate}
  - label: Settings
    name: settings
    icon: tune
    i18n:
      structure: single_file
    files:
      - label: Site Data
        name: site
        file: src/_data/site.json
        i18n: true
        fields:
          - {label: Name, name: name, widget: string, i18n: true}
          - {label: Description, name: description, widget: text, i18n: true}
          - {label: URL, name: url, widget: string, i18n: duplicate}
          - {label: Author Name, name: authorName, widget: string, i18n: duplicate}
          - {label: Author Email, name: authorEmail, widget: string, i18n: duplicate}
          - {label: Author Website, name: authorWebsite, widget: string, i18n: duplicate}

